In [1]:
# 1. Crear un array de ceros
# 2. Mostrar configuración de NumPy
# 3. Inicializar un vector de longitud 10 con ceros
# 4. Obtener información de la función add (in English)
# 5. Establecer el valor 1 en la posición 4 de un vector de ceros
# 6. Generar un array de enteros del 10 al 49
# 7. Invertir un array de 0 a 49
# 8. Reestructurar un array de 9 elementos en una matriz 3×3
# 9. Encontrar índices de elementos no cero
# 10. Matriz identidad de tamaño 3×3
# 11. Generate a random 3D array (in English)
# 12. Normalizar valores mínimo y máximo de una matriz 10×10
# 13. Calcular la media de 30 números aleatorios
# 14. Rellenar bordes con unos y centro con ceros
# 15. Comportamiento de NaN e infinitos (in English)
# 16. Crear una matriz diagonal con valores desplazados
# 17. Tablero de ajedrez de 8×8 con ceros y unos
# 18. Índice multilínea con np.unravel_index
# 19. Repetir un patrón bidimensional 4 veces
# 20. Escalar una matriz aleatoria 5×5 al rango [0,1]
# 21. Definir un dtype para colores RGBA
# 22. Matrix multiplication of ones (in English)
# 23. Negativizar elementos en un rango dado
# 24. Sumar rangos con numpy y Python built-in (in English)
# 25. Operaciones bitwise y aritméticas diversas
# 26. Division and floor division edge cases (in English)
# 27. Redondear números uniformes con truncamiento
# 28. Obtener partes enteras de números aleatorios
# 29. Añadir vectores en matrices
# 30. Crear un array desde un generador
# 31. Generar valores intermedios con linspace
# 32. Ordenar un vector aleatorio
# 33. Sumar todos los elementos de un array
# 34. Comparar arrays booleanos
# 35. Hacer un array no modificable
# 36. Convertir coordenadas cartesianas a polares
# 37. Reemplazar el valor máximo por cero
# 38. Array estructurado 10×10
# 39. Determinante por outer subtraction
# 40. Límites de tipos NumPy
# 41. Mostrar matriz grande completa
# 42. Valor más cercano en vector
# 43. Array con posición y color
# 44. Distancias con scipy.spatial (in English)
# 45. Convertir tipo sin copiar
# 46. Leer datos con genfromtxt
# 47. Iterar índices y valores
# 48. Matriz Gaussiana 2D
# 49. Colocar unos aleatoriamente
# 50. Centralizar datos por fila
# 51. Normalizar matriz aleatoria 5×5
# 52. Multiplicar matriz 5×3 por 3×2
# 53. Dividir array 1D de tamaño 20 en 4 partes
# 54. Reemplazar valores mayores que 5 por 5
# 55. Convertir lista de Python a array
# 56. Valores únicos y conteo
# 57. Crear matriz tridiagonal
# 58. Crear vector de enteros 10 a 49 (repetido)
# 59. Subsetting y asignación condicional
# 60. Media, varianza y desviación estándar
# 61. Broadcasting y potencias
# 62. Transponer matrices
# 63. Intercambiar filas y columnas
# 64. Aplanar un array
# 65. Crear meshgrid
# 66. Extraer centro de matriz
# 67. Convertir float a int con truncamiento
# 68. Invertir bits de array binario
# 69. Suma acumulada
# 70. Producto acumulado
# 71. Producto punto entre vectores
# 72. Determinante de 3×3
# 73. Inversa de matriz
# 74. Resolver sistema lineal Ax=b
# 75. Covarianza y correlación
# 76. Histograma de datos
# 77. Concatenar arrays
# 78. Stack vertical y horizontal
# 79. Dividir con hsplit
# 80. Indexación booleana
# 81. Indexación fancy
# 82. Unique con retorno de índices
# 83. Nonzero en matriz 2D
# 84. Matriz identidad con desplazamiento k
# 85. Bordes ceros centro unos
# 86. Permutar aleatoriamente elementos
# 87. Establecer diagonal principal
# 88. Extraer diagonal
# 89. Matriz tridiagonal (generalizada)
# 90. Uniform random ints entre 0 y 10
# 91. Distribución geométrica
# 92. Distribución normal
# 93. Elegir elementos aleatorios de lista
# 94. Barajar filas de matriz
# 95. Añadir filas a matriz
# 96. Eliminar columna
# 97. Insertar columna
# 98. Ordenar filas
# 99. Lexsort con dos columnas
# 100. Obtener submatriz de esquina superior

### EJERCICIO 1
Crear un array de ceros


In [2]:
import numpy as np
array_zeros = np.zeros((3, 3))
print("Array de ceros:\n", array_zeros)

Array de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### EJERCICIO 2
Imprime la versión de numpy y la configuración.

In [6]:
print(np.__version__)
np.show_config()

2.2.4
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3gj71u4o/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

In [ ]:
print(np.__version__)
np.show_config()

### EJERCICIO 3
Crea un vector nulo de tamaño 10

In [7]:
array_nulo = np.zeros(10)
print(array_nulo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### EJERCICIO 4
obtener la documentación de la función add de numpy

In [9]:
#python -c "import numpy; numpy.info(numpy.add)"

### EJERCICIO 5
Crea un vector nulo de tamaño 10 pero el quinto valor debe ser 1

In [13]:
v = np.array([0,0,0,0,1,0,0,0,0,0])
print(v)

[0 0 0 0 1 0 0 0 0 0]


### EJERCICIO 5
Alternativa rapida

In [14]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### EJERCICIO 6
Crear un vector con los valores del 10 al 49

In [16]:
print(np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### EJERCICIO 7
Invierte un vector (el primer elemento pasa a ser el último)

In [ ]:
invertir = np.arange(10, 50)[::-1]
print(invertir)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### EJERCICIO 8
Crea una matriz de 3x3 con valores que van del 0 al 8

In [19]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### EJERCICIO 9
Encuentra los índices de los elementos no nulos en [1, 2, 0, 0, 4, 0]

In [20]:
# Encuentra los índices de los elementos no nulos en [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


### EJERCICIO 10
 Crea una matriz identidad de 3x3

In [21]:
m = np.eye(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### EJERCICIO 10
EXTENSION
Matriz de identidad de 4x4 de derecha a izquerda

In [23]:
mcuatro= np.eye(4)[::-1]
print(mcuatro)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


### EJERCICIO 11
Crea un arreglo de 3x3x3 con valores aleatorios

In [30]:
z = np.random.random((3, 3, 3))
print(z)

[[[0.69874104 0.80413731 0.64584783]
  [0.19765502 0.74758715 0.52418043]
  [0.09933788 0.60478453 0.80478129]]

 [[0.69871867 0.53464663 0.36339453]
  [0.65989262 0.70488079 0.71808331]
  [0.75151047 0.97754435 0.99951178]]

 [[0.51964578 0.57617796 0.99045098]
  [0.8387071  0.17129101 0.33062286]
  [0.10178928 0.29252047 0.27569138]]]


### EJERCICIO 12
Crea un arreglo de 10x10 con valores aleatorios y encuentra el valor mínimo y el valor máximo

In [32]:
za = np.random.random((10, 10))
print("Valor mínimo:", za.min())
print("Valor máximo:", za.max())
print(za)

Valor mínimo: 0.004052370390456361
Valor máximo: 0.9873421323696551
[[0.00405237 0.28055878 0.00636563 0.54985977 0.71433713 0.42573665
  0.78124861 0.83029836 0.69692401 0.21279676]
 [0.67817386 0.3445625  0.73216661 0.70556713 0.40861292 0.67816278
  0.32691003 0.78895139 0.84626367 0.98734213]
 [0.23338899 0.22072616 0.92851178 0.4609736  0.02749663 0.84732943
  0.23456846 0.16769315 0.19004637 0.4638586 ]
 [0.16249011 0.92729162 0.01889065 0.05124032 0.68427875 0.35202926
  0.32196448 0.01092539 0.74539148 0.28783191]
 [0.29708033 0.01053471 0.30497734 0.02425081 0.98266376 0.231445
  0.56233874 0.1424418  0.58499325 0.83353248]
 [0.56720955 0.22795802 0.50658967 0.50908899 0.1814971  0.50414813
  0.26670018 0.87274822 0.55292572 0.7641051 ]
 [0.0965585  0.51879637 0.94380887 0.29435741 0.23776869 0.62015222
  0.75680244 0.80265038 0.48751987 0.21889136]
 [0.45177614 0.23630719 0.73370285 0.89970388 0.71910891 0.55519443
  0.52908761 0.55139482 0.60946309 0.30483923]
 [0.05702729 0

### EJERCICIO 13
Crea un vector aleatorio de tamaño 30 y encuentra el valor medio

In [36]:
z = np.random.random((30))
print("valor medio:", z.mean())
print(z)

valor medio: 0.5723937058874349
[0.90209179 0.86906848 0.49178905 0.62938906 0.37876191 0.78280768
 0.79813285 0.57465201 0.59183979 0.26869608 0.17476266 0.95147308
 0.62541991 0.93490994 0.8092054  0.35347813 0.99036434 0.25398953
 0.11051574 0.37001429 0.6037169  0.88416275 0.35263635 0.28087716
 0.74228252 0.07785189 0.29667235 0.53776926 0.54694491 0.98753536]


### EJERCICIO 14
Crea un arreglo 2D con 1 en los bordes y 0 en el interior

In [41]:
a2d = np.ones((5, 5))
a2d[1:-1, 1:-1] = 0
print(a2d)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### EJERCICIO 15
¿Cuál es el resultado de la siguiente expresión?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

0.3 == 3 * 0.1

**Resultados:**   
### EJERCICIO 15

- `0 * np.nan` → `nan` (cualquier operación con nan da nan)
- `np.nan == np.nan` → `False` (nan nunca es igual a nan)
- `np.inf > np.nan` → `False` (nan no es comparable, cualquier comparación con nan es False)
- `np.nan - np.nan` → `nan` (operaciones entre nan siguen siendo nan)
- `0.3 == 3 * 0.1` → `False` (por precisión de punto flotante, 0.3 no es exactamente igual a 3*0.1)


### EJERCICIO 16
Crea una matriz de 5x5 con los valores 1, 2, 3, 4 justo debajo de la diagonal principal

In [42]:
# Crear una matriz de 5x5 con los valores 1,2,3,4 justo debajo de la diagonal principal
matriz = np.diag([1, 2, 3, 4], k=-1)
print(matriz)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### EJERCICIO 17
Crea una matriz de 8x8 y rellénala con un patrón de tablero de ajedrez

In [57]:
ajedrez = np.zeros((8, 8), dtype='int')
ajedrez[1::2, ::2] = 1
ajedrez[::2, 1::2] = 1
print(ajedrez)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### EJERCICIO 18
Considera un arreglo de forma (6, 7, 8), ¿cuál es el índice (x, y, z) del elemento número 100?

In [ ]:
ejercicio18 = np.zeros((6, 7, 8))
indice_100 = np.unravel_index(100, ejercicio18.shape)
print(indice_100)

(np.int64(1), np.int64(5), np.int64(4))
Índice del elemento número 100: (np.int64(1), np.int64(5), np.int64(4))


### EJERCICIO 19
Cree una matriz de tablero de ajedrez de 8x8 utilizando la función de mosaico

In [58]:
ajedrez = np.array([[0, 1], [1, 0]])
ajedrez = np.tile(ajedrez, (4, 4))
print(ajedrez)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### EJERCICIO 20
Normaliza una matriz aleatoria de 5x5.

In [22]:
# 1) Generar matriz aleatoria 5×5
mat = np.random.rand(5, 5)

# 2) Normalizar globalmente al rango [0,1]
mat_norm = (mat - mat.min()) / (mat.max() - mat.min())
print(mat)

[[0.76842616 0.48873153 0.8218595  0.51101133 0.29798818]
 [0.1252775  0.01741595 0.04565216 0.28670563 0.31789998]
 [0.84444358 0.84268422 0.52200669 0.23321949 0.78862955]
 [0.60196049 0.62614766 0.59731475 0.42626024 0.70735134]
 [0.46181251 0.90805222 0.34938238 0.05536274 0.71420383]]


### EJERCICIO 21
Create a custom dtype that describes a color as four unisgned bytes

In [24]:
color = np.dtype([
    ("r", np.ubyte, 1),
    ("g", np.ubyte, 1),
    ("b", np.ubyte, 1),
    ("a", np.ubyte, 1)])
print(color)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


### EJERCICIO 22
Multiplica una matriz de 5×3 por una matriz de 3×2 (producto matricial real)

In [25]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### EJERCICIO 23
Negativizar elementos en un rango dado

In [26]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


### EJERCICIO 24
Sumar rangos con numpy y Python built-in

In [27]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


### EJERCICIO 25
Operaciones bitwise y aritméticas diversas

In [ ]:
# Z**Z
# 2 << Z >> 2
# Z < -Z
# 1j * Z
# Z / 1 / 1
# Z < Z > Z

### EJERCICIO 26
Division and floor division edge cases

In [28]:
print(np.array(0) // np.array(0))
print(np.array(0) // np.array(0.))
print(np.array(0) / np.array(0))
print(np.array(0) / np.array(0.))

0
nan
nan
nan


C:\Users\56997\AppData\Local\Temp\ipykernel_10756\2371707608.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\56997\AppData\Local\Temp\ipykernel_10756\2371707608.py:2: RuntimeWarning: invalid value encountered in floor_divide
  print(np.array(0) // np.array(0.))
C:\Users\56997\AppData\Local\Temp\ipykernel_10756\2371707608.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\56997\AppData\Local\Temp\ipykernel_10756\2371707608.py:4: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0.))


### EJERCICIO 27
Redondear números uniformes con truncamiento

In [29]:
Z = np.random.uniform(-10, +10, 10)
print(np.trunc(Z + np.copysign(0.5, Z)))

[-7. -1. -5.  5.  5.  2. -3. -0.  5. -3.]


### EJERCICIO 28
Obtener partes enteras de números aleatorios

In [30]:
Z = np.random.uniform(0, 10, 10)
print(Z - Z % 1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(Z.astype(int))
print(np.trunc(Z))

[5. 1. 5. 2. 6. 0. 5. 6. 7. 7.]
[5. 1. 5. 2. 6. 0. 5. 6. 7. 7.]
[5. 1. 5. 2. 6. 0. 5. 6. 7. 7.]
[5 1 5 2 6 0 5 6 7 7]
[5. 1. 5. 2. 6. 0. 5. 6. 7. 7.]


### EJERCICIO 29
Añadir vectores en matrices

In [31]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### EJERCICIO 30
Crear un array desde un generador

In [32]:
def generate():
    for x in range(10): yield x
Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### EJERCICIO 31
Generar valores intermedios con linspace

In [33]:
Z = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(Z)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### EJERCICIO 32
Ordenar un vector aleatorio

In [34]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.08928306 0.146392   0.17790951 0.19002469 0.27767787 0.3384577
 0.3677248  0.56005184 0.64149597 0.72025064]


### EJERCICIO 33
Sumar todos los elementos de un array

In [39]:
Z = np.arange(10)
print(np.add.reduce(Z))

45


### EJERCICIO 34
Comparar arrays booleanos

In [40]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(np.allclose(A,B))

False


### EJERCICIO 35
Hacer un array no modificable

In [43]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1 generará error
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### EJERCICIO 36
Convertir coordenadas cartesianas a polares

In [46]:
Z = np.random.random((10,2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print("Esta es la R ", R)
print("Esta es la T ", T)

Esta es la R  [0.69714593 0.30840323 0.58271948 0.81628553 0.77888234 0.77592936
 0.87276417 0.87324266 0.80303556 0.48136218]
Esta es la T  [0.669364   0.05652725 1.51676033 0.79736732 0.01631222 0.05176193
 0.4789235  1.3154792  0.27661538 0.07602292]


### EJERCICIO 37
Remplazar el valor maximo por cero


In [47]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.54701226 0.03497119 0.3879622  0.35954123 0.27687125 0.93176758
 0.         0.01158946 0.35207096 0.49847   ]


### EJERCICIO 38
Crear un array estructurado con malla 10×10

In [48]:
Z = np.zeros((10,10), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

### EJERCICIO 39
Determinante de una matriz definida por outer subtraction

In [49]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


### EJERCICIO 40
Obtener límites de tipos enteros y flotantes

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min, np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min, np.finfo(dtype).max, np.finfo(dtype).eps)

-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38 1.1920929e-07
-1.7976931348623157e+308 1.7976931348623157e+308 2.220446049250313e-16


### EJERCICIO 41
Configurar printoptions para matrices grandes

In [51]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

### EJERCICIO 42
Encontrar el valor más cercano en un vector

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z - v)).argmin()
print(Z[index])

30


### EJERCICIO 43
Estructurar posiciones y colores en un array

In [55]:
Z = np.zeros(10, dtype=[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


### EJERCICIO 44
Calcular distancias con scipy.spatial

In [56]:
import scipy.spatial
d = np.random.random((10,2))
D = scipy.spatial.distance.cdist(d,d)
print(D)

[[0.         0.69715326 0.31735692 1.09408487 0.27587961 1.08147122
  0.37677345 0.43363228 1.16777041 0.7697314 ]
 [0.69715326 0.         0.40092126 0.58011549 0.52585588 0.41778672
  0.343978   0.31383023 0.58130543 0.09650767]
 [0.31735692 0.40092126 0.         0.78698963 0.14118118 0.76573061
  0.18707811 0.11709751 0.85288311 0.48588984]
 [1.09408487 0.58011549 0.78698963 0.         0.8291253  0.32566902
  0.85260534 0.67171293 0.14331533 0.61408023]
 [0.27587961 0.52585588 0.14118118 0.8291253  0.         0.85757556
  0.31950723 0.21436688 0.91395791 0.61573002]
 [1.08147122 0.41778672 0.76573061 0.32566902 0.85757556 0.
  0.75638326 0.65321882 0.23155391 0.40014867]
 [0.37677345 0.343978   0.18707811 0.85260534 0.31950723 0.75638326
  0.         0.22907809 0.89006972 0.40205238]
 [0.43363228 0.31383023 0.11709751 0.67171293 0.21436688 0.65321882
  0.22907809 0.         0.73578941 0.40640184]
 [1.16777041 0.58130543 0.85288311 0.14331533 0.91395791 0.23155391
  0.89006972 0.73578

### EJERCICIO 45
Convertir tipo de datos sin copiar

In [57]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### EJERCICIO 46
Leer datos de un archivo con genfromtxt

In [60]:
import urllib.request
url = "https://people.sc.fsu.edu/~jburkardt/data/csv/airtravel.csv"
response = urllib.request.urlopen(url)
data = response.read().decode('utf-8').splitlines()
Z = np.genfromtxt(data, delimiter=",", skip_header=1)

### EJERCICIO 47
Enumerar elementos con ndenumerate y ndindex

In [61]:
Z = np.arange(9).reshape(3,3)
for idx, val in np.ndenumerate(Z): print(idx, val)
for idx in np.ndindex(Z.shape): print(idx, Z[idx])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### EJERCICIO 48
Generar una matriz Gaussiana 2D

In [62]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0*sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

### EJERCICIO 49
Poner valores 1 de forma aleatoria en una matriz

In [63]:
n, p = 10, 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(n*n, p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


### EJERCICIO 50
Centrar datos restando la media por fila

In [67]:
X = np.random.rand(5,10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.30731179  0.12827921  0.52757963 -0.27768512  0.37455416  0.09954349
  -0.2113045   0.04455668 -0.17555315 -0.20265861]
 [ 0.28991255  0.06298696  0.17353039  0.0271414   0.26867634  0.08398543
  -0.36360723 -0.32889971  0.22681785 -0.44054399]
 [ 0.28805707  0.02268923 -0.06243214 -0.52545564 -0.05598517  0.17952402
   0.06282694  0.1484058  -0.30105642  0.2434263 ]
 [ 0.04524512 -0.40490437  0.32319856 -0.00602306  0.30695368 -0.49913737
   0.41017385 -0.50289942  0.22574543  0.10164757]
 [ 0.03170657  0.5028098  -0.1213321  -0.30772168 -0.0888152  -0.23278414
   0.00533481 -0.18682498 -0.14228202  0.53990894]]


### EJERCICIO 51
Normalizar matriz aleatoria 5×5

In [68]:
M=np.random.rand(5,5)
print((M-M.min())/(M.max()-M.min()))

[[0.44508914 0.06004767 0.35109547 0.08816394 0.65369961]
 [0.95319715 0.47703444 0.63537408 0.65290711 0.55361288]
 [0.09732618 0.39721939 0.14310047 0.10539153 0.67530422]
 [0.71201501 0.81495838 0.4321633  0.48394867 0.90638335]
 [0.3167876  0.66589229 1.         0.37352306 0.        ]]


### EJERCICIO 52
Multiplicar matriz 5×3 por 3×2

In [69]:
A=np.random.rand(5,3);B=np.random.rand(3,2)
print(A.dot(B))

[[0.57343767 0.32710457]
 [0.14727939 0.12955455]
 [0.44064415 0.41224271]
 [0.45693755 0.36057768]
 [0.33343555 0.22017758]]


### EJERCICIO 53
Dividir array 1D de tamaño 20 en 4 partes

In [70]:
Z=np.arange(20)
print(np.array_split(Z,4))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]


### EJERCICIO 54
Reemplazar valores mayores que 5 por 5

In [71]:
Z=np.arange(10)
Z[Z>5]=5
print(Z)

[0 1 2 3 4 5 5 5 5 5]


### EJERCICIO 55
Convertir lista de Python a array

In [72]:
L=[1,2,3,4]
print(np.array(L))

[1 2 3 4]


### EJERCICIO 56
Valores únicos y conteo

In [73]:
Z=np.array([1,2,2,3,3,3])
print(np.unique(Z,return_counts=True))

(array([1, 2, 3]), array([1, 2, 3]))


### EJERCICIO 57
Crear matriz tridiagonal

In [74]:
n=5
A=np.diag(np.ones(n-1),-1)+np.diag(np.ones(n),0)+np.diag(np.ones(n-1),1)
print(A)

[[1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]]


### EJERCICIO 58
Crear vector de enteros 10 a 49

In [75]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### EJERCICIO 59
Subsetting y asignación condicional

In [76]:
Z=np.arange(10)
print(Z[::2])
Z[::2]=-1
print(Z)

[0 2 4 6 8]
[-1  1 -1  3 -1  5 -1  7 -1  9]


### EJERCICIO 60
Media, varianza y desviación estándar

In [77]:
Z=np.random.rand(10)
print(Z.mean(),Z.var(),Z.std())

0.5516684152340879 0.05001766216712691 0.22364628806918954


### EJERCICIO 61
Broadcasting y potencias

In [78]:
Z=np.arange(1,5)
print(Z**2)

[ 1  4  9 16]


### EJERCICIO 62
Transponer matrices

In [79]:
Z=np.arange(6).reshape(2,3)
print(Z.T)

[[0 3]
 [1 4]
 [2 5]]


### EJERCICIO 63
Intercambiar filas y columnas

In [80]:
Z=np.arange(9).reshape(3,3)
print(Z[[2,0,1]])
print(Z[:,[2,0,1]])

[[6 7 8]
 [0 1 2]
 [3 4 5]]
[[2 0 1]
 [5 3 4]
 [8 6 7]]


### EJERCICIO 64
Aplanar un array

In [81]:
Z=np.arange(6).reshape(2,3)
print(Z.flatten())

[0 1 2 3 4 5]


### EJERCICIO 65
Crear meshgrid

In [82]:
x=np.linspace(0,1,3)
y=np.linspace(0,1,3)
print(np.meshgrid(x,y))

(array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ],
       [0. , 0.5, 1. ]]), array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]]))


### EJERCICIO 66
Extraer centro de matriz

In [83]:
Z=np.arange(25).reshape(5,5)
print(Z[1:-1,1:-1])

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


### EJERCICIO 67
Convertir float a int con truncamiento

In [84]:
Z=np.random.rand(5)
print(Z.astype(int))

[0 0 0 0 0]


### EJERCICIO 68
Invertir bits de array binario

In [85]:
Z=np.array([1,0,1,0])
print(1-Z)

[0 1 0 1]


### EJERCICO 69
Suma acumulada

In [86]:
Z=np.arange(5)
print(Z.cumsum())

[ 0  1  3  6 10]


### EJERCICIO 70
Producto acumulado

In [87]:
Z=np.arange(1,5)
print(Z.cumprod())

[ 1  2  6 24]


### EJERCICIO 71
Producto punto entre vectores

In [88]:
A=np.array([1,2]);B=np.array([3,4])
print(np.dot(A,B))

11


### EJERCICIO 72
Determinante de 3×3

In [89]:
A=np.random.rand(3,3)
print(np.linalg.det(A))

0.22320269292452083


### EJERCICIO 73
Inversa de matriz

In [90]:
A=np.eye(3);
print(np.linalg.inv(A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### EJERCICIO 74
Resolver sistema lineal Ax=b

In [91]:
A=np.random.rand(3,3);b=np.random.rand(3)
print(np.linalg.solve(A,b))

[ 1.90160436  1.61155024 -2.03918787]


### EJERCICIO 75
Covarianza y correlación

In [92]:
X=np.random.rand(3,10)
print(np.cov(X))
print(np.corrcoef(X))

[[ 0.10911809  0.02715343 -0.01569166]
 [ 0.02715343  0.08719828  0.00998084]
 [-0.01569166  0.00998084  0.12346458]]
[[ 1.          0.27836998 -0.13519152]
 [ 0.27836998  1.          0.0961927 ]
 [-0.13519152  0.0961927   1.        ]]


### EJERCICIO 76
Histograma de datos

In [93]:
Z=np.random.randn(1000)
print(np.histogram(Z,bins=10))

(array([  6,  11,  56, 166, 231, 219, 159, 105,  38,   9]), array([-3.24053611, -2.61558322, -1.99063033, -1.36567744, -0.74072456,
       -0.11577167,  0.50918122,  1.13413411,  1.759087  ,  2.38403989,
        3.00899278]))


### EJERCICIO 77
Concatenar arrays

In [94]:
A=np.ones((2,3));B=np.zeros((2,3))
print(np.concatenate([A,B],axis=0))

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


### EJERCICIO 78
Stack vertical y horizontal

In [95]:
A=np.ones((2,3));B=np.zeros((2,3))
print(np.vstack([A,B]),np.hstack([A,B]))

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


### EJERCICIO 79
Dividir con hsplit

In [96]:
Z=np.arange(16).reshape(4,4)
print(np.hsplit(Z,2))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


### EJERCICIO 80
Indexación booleana

In [97]:
Z=np.arange(10)
print(Z[Z%2==0])

[0 2 4 6 8]


### EJERCICIO 81
Indexación fancy

In [98]:
Z=np.arange(10)
print(Z[[2,5,7]])

[2 5 7]


### EJERCICIO 82
Unique con retorno de índices

In [99]:
Z=np.array([1,2,2,3,3])
print(np.unique(Z,return_index=True))

(array([1, 2, 3]), array([0, 1, 3]))


### EJERCICIO 83
Nonzero en matriz 2D

In [100]:
Z=np.array([[1,0],[0,1]])
print(np.nonzero(Z))

(array([0, 1]), array([0, 1]))


### EJERCICIO 84
Matriz identidad con desplazamiento k

In [101]:
print(np.eye(4,k=1))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


### EJERCICIO 85
Bordes ceros centro unos

In [102]:
Z=np.ones((5,5));Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### EJERCICIO 86
Permutar aleatoriamente elementos

In [103]:
Z=np.arange(10)
print(np.random.permutation(Z))

[7 2 6 3 1 8 5 9 4 0]


### EJERCICIO 87
Establecer diagonal principal

In [104]:
Z=np.zeros((4,4));np.fill_diagonal(Z,5)
print(Z)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


### EJERCICIO 88
Extraer diagonal

In [105]:
Z=np.arange(9).reshape(3,3)
print(np.diag(Z))

[0 4 8]


### EJERCICIO 89
Matriz tridiagonal

In [106]:
def tri(n):
    A=np.zeros((n,n));
    for i in range(n):
        for j in [i-1,i,i+1]:
            if 0<=j<n: A[i,j]=1
    return A
print(tri(5))

[[1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]]


### EJERCICIO 90
Uniform random ints entre 0 y 10

In [107]:
print(np.random.randint(0,10,10))

[5 5 5 4 8 7 6 2 3 5]


### EJERCICIO 91
Distribución geométrica

In [108]:
print(np.random.geometric(p=0.3, size=10))

[ 8  6  2  1  1  2  2 12  1  1]


### EJERCICIO 92
Distribución normal

In [109]:
print(np.random.normal(loc=0,scale=1,size=10))

[ 1.20082332 -0.83629427 -0.66199822  1.15138774  1.40849157  0.96900695
  0.09562829 -0.99106333 -0.45306718 -0.69059512]


### EJERCICIO 93
Elegir elementos aleatorios de lista

In [110]:
print(np.random.choice([1,2,3,4,5], size=5))

[5 3 2 1 4]


### EJERCICIO 94
Barajar filas de matriz

In [111]:
Z=np.arange(9).reshape(3,3)
np.random.shuffle(Z)
print(Z)

[[0 1 2]
 [6 7 8]
 [3 4 5]]


### EJERCICIO 95
Añadir filas a matriz

In [112]:
Z=np.ones((2,3));
print (np.vstack([Z,Z]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### EJERCICIO 96
Eliminar columna

In [113]:
Z=np.arange(9).reshape(3,3)
print(np.delete(Z,1,axis=1))

[[0 2]
 [3 5]
 [6 8]]


### EJERCICIO 97
Insertar columna

In [114]:
Z=np.arange(9).reshape(3,3)
print(np.insert(Z,1,5,axis=1))

[[0 5 1 2]
 [3 5 4 5]
 [6 5 7 8]]


### EJERCICIO 98
Ordenar filas

In [115]:
Z=np.random.randint(0,10,(3,3))
print(np.sort(Z,axis=1))

[[2 2 6]
 [2 7 9]
 [2 3 9]]


### EJERCICIO 99
Lexsort con dos columnas

In [116]:
A=np.array([3,1,2]);B=np.array([9,8,7])
print(np.lexsort((B,A)))

[1 2 0]


### EJERCICIO 100
Obtener submatriz de esquina superior

In [117]:
Z=np.arange(16).reshape(4,4)
print(Z[:2,:2])

[[0 1]
 [4 5]]
